import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ScrollProvider from "./components/ScrollProvider";
import ClientScrollbar from "./components/ClientScrollbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <title>Codantix Tech </title>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Locomotive wrapper (creates data-scroll-container and instance) */}
        <ScrollProvider>
          {children}
        </ScrollProvider>

        {/* Client-only glowing scrollbar (will attach to Locomotive / container / window) */}
        <ClientScrollbar />
      </body>
    </html>
  );
}