// app/layout.jsx  (server component)
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ScrollProvider from "./components/ScrollProvider";
import ClientScrollbar from "./components/ClientScrollbar";
import Header from "./components/Header"; // <-- move header here (outside the scroll container)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Codantix Tech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Header MUST be outside ScrollProvider to keep it truly fixed */}
        <Header />

        {/* Locomotive wrapper (creates data-scroll-container and instance) */}
        <ScrollProvider>
          {children}
        </ScrollProvider>

        {/* Client-only glowing scrollbar (will attach to Locomotive / container / window) */}
        <ClientScrollbar />
      </body>
    </html>
  );
}
